### ISSUE TITLE
Undocumented Amazon key

### ISSUE THREAD

**Issue by derwaldgeist** [Exartu/Exartu-CRM#37]
I tried to set this project up, as it looked promising. However, on startup I get this error:

```bash
W20150928-09:18:07.450(2)? (STDERR) Error: Match error: Missing key 'AWSAccessKeyId'
W20150928-09:18:07.450(2)? (STDERR)     at packages/check/match.js:312:1
W20150928-09:18:07.450(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150928-09:18:07.450(2)? (STDERR)     at checkSubtree (packages/check/match.js:311:1)
W20150928-09:18:07.450(2)? (STDERR)     at check (packages/check/match.js:32:1)
W20150928-09:18:07.450(2)? (STDERR)     at new Slingshot.Directive (packages/edgee:slingshot/lib/directive.js:111:1)
W20150928-09:18:07.450(2)? (STDERR)     at Object.Slingshot.createDirective (packages/edgee:slingshot/lib/directive.js:81:1)
W20150928-09:18:07.450(2)? (STDERR)     at app/server/storage/slingshot.js:7:11
W20150928-09:18:07.450(2)? (STDERR)     at app/server/storage/slingshot.js:29:3
```
Seems as if it is using an Amazon S3 bucket and tries to retrieve the credentials from Meteor.settings. I think this should be documented in the Readme.

**Comment by c0cl3c** [comment]
I too am getting this issue. Unable to run for testing and cannot find an issue.

**Comment by c0cl3c** [comment]
A solution I meant. Searched everywhere. Just doesn't want to run.

**Comment by derwaldgeist** [comment]
I got it to work, since I am using Slingshot myself. You have to create an Amazon AWS account, set up an S3 bucket and add your AWS S3 credentials to the Meteor settings.json file. This allowed me to start the server up and have a look at the CRM system. But still, the (undocumented) configuration was not complete, I got some errors and could not use everything. I got the feeling that this project is mainly used by consultants of the developing company and not intended to be used by anyone else.

**Comment by c0cl3c** [comment]
Thanks for that derwaldgeist. I will give it a shot. I'm keen on seeing a proper Meteor CRM come out one day that can compete with the likes of SugarCRM. So far I have not been able to find anything that has real time updating in the browser. Would be a good feature for Service departments with many technicians in the field. Add Desktop Notifications and you have a winner.

**Comment by greggdourgarian** [comment]
hi c0 and derwaldgeist...I'm Gregg, the owner of Aida Creative, the company behind this repo, Exartu.  Thanks for pointing out the bugs.   We'll try to get a fix in soon.   We used to be pretty careful about maintaining the repo so other developers could run with it, but we never got much reaction from the Meteor community.  Maybe time to reevaluate...?

**Comment by rodrigocprates** [comment]
hi @greggdourgarian 

do we must use an Amazon account to get it running? is there any other alternative?

**Comment by greggdourgarian** [comment]
Hi Rodrigo…yes we require it for s3 storage.   Tx!

**Comment by derwaldgeist** [comment]
Just as a side-note: You can get a 1-year free Amazon Web Services account. So you could try it out without additional costs, as long as you don't want to set-up a production ready environment, since the free tier is somewhat limited.

**Comment by rodrigocprates** [comment]
Cool! I didn't know that.

The point that I was think is that, if I just want to check out how Exartu
works I need to setup it.

What about if we have an local option to smoothly run Meteor and get it up?


2015-11-06 13:16 GMT-02:00 Tom Brückner <notifications@github.com>:

> Just as a side-note: You can get a 1-year free Amazon Web Services
> account. So you could try it out without additional costs, as long as you
> don't want to set-up a production ready environment, since the free tier is
> somewhat limited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Exartu/Exartu-CRM/issues/37#issuecomment-154434792>.
>



-- 

*Atenciosamente, Rodrigo PRATES*

**Comment by greggdourgarian** [comment]
Hey Rodrigo
We’d love to have more contributions to the project, so feel code Amazon S3 an option and issue a pull request.
